### ISSUE TITLE
Suggestion: copy/paste initialization guide or script

### ISSUE THREAD

**Issue by alexellis** [ibuildthecloud/k3s#10]
Hey Darren,

Would you be able to put together something someone could copy/paste without thinking about it? Or maybe an initialization script that works on a base Ubuntu 16/18.x machine?

I was thinking of having a play with this but it looks like it might take a bit longer than I had.

Alex

**Comment by ibuildthecloud** [comment]
I updated the README quite a bit plus fully repackaged k3s.  I hope it's about as simple as it can get at this point.

**Comment by alexellis** [comment]
Sounds great
