### ISSUE TITLE
Missing /root/.kube/k3s.yaml

### ISSUE THREAD

**Issue by MichaelJCole** [ibuildthecloud/k3s#15]
Hi there, thanks for your project.  We're excited to be using it!

I noticed this bug.  The logs say the config file was written, but it wasn't:
```
root@spot-47:/var/lib/rancher/k3s# journalctl -u k3s
...
Feb 01 20:06:51 spot-47 k3s[540]: time="2019-02-01T20:06:51.209386967Z" level=error msg="Failed to generate kubeconfig: server https://localhost:6443/cacerts is not trusted: Ge
Feb 01 20:06:51 spot-47 k3s[540]: time="2019-02-01T20:06:51.209534311Z" level=info msg="Wrote kubeconfig /root/.kube/k3s.yaml"
...

root@spot-47:/var/lib/rancher/k3s# cat /root/.kube/k3s.yaml
cat: /root/.kube/k3s.yaml: No such file or directory

```
Thanks!

**Comment by ibuildthecloud** [comment]
@MichaelJCole hmmm.  Let me look into this.  Does systemd do some automatic blackmagic and make `/root` a private directory?

**Comment by ibuildthecloud** [comment]
@MichaelJCole I haven't looked at this yet but just wanted to call out that you can control where that file is written to with `--write-kubeconfig /somewhere/else` so putting somewhere besides /root might be a decent workaround.

**Comment by MichaelJCole** [comment]
Hi @ibuildthecloud I don't think systemd does any black magic on it.  

The first line had an error: "server https://localhost:6443/cacerts is not trusted:"  which may be the root cause.  I'm not sure why that is or how to work around it.

The second line looks like a console messaging bug, possibly from upstream.

Thanks for looking at it!

Michael

**Comment by ibuildthecloud** [comment]
Thanks, knowing it's raspberry pi helps a lot.  Things are so much slower that I could be hitting a timeout somewhere.  I'll test on rpi.  @MichaelJCole Which Raspberry PI are you using?  I typically just test on rpi3 b.

**Comment by MichaelJCole** [comment]
Ok yes! It's a 3. Thanks!

**Comment by liyimeng** [comment]
alpine Linux have the same issue.

**Comment by ibuildthecloud** [comment]
@MichaelJCole I haven't yet been able to reproduce this, could you possibly try v0.1.0-rc3 that I just released and see if you still get the same behavior.

@liyimeng I believe the issue you are seeing is different.  There was a deadlock issue on startup while generating the TLS certs that would cause the server to hang on startup

**Comment by MichaelJCole** [comment]
@ibuildthecloud I moved on to another project, so I won't have the hardware for it :-(  If you're not able to reproduce, then it can probably be closed.  It would be cool to have a "known working config" to use k3s with on Pi 3's - or a blog post.  I'm really interested in your project!

**Comment by ibuildthecloud** [comment]
@MichaelJCole Thanks. We definitely have writes up in the works right.  I'll close this issue for now.
