### ISSUE TITLE
artifact-free repo 

### ISSUE THREAD

**Issue by ekoontz** [ibuildthecloud/k3s#2]
why is this so huge? is there a way to break out the source into a separate repo so people can just download that and build/fetch the artifacts when they choose?

**Comment by ibuildthecloud** [comment]
@ekoontz Are you saying the git clone is huge?  This is a fork of https://github.com/kubernetes/kubernetes, it's a massive repo.  I need the git history so I can manage the patches and stuff.

**Comment by ekoontz** [comment]
Ah ok - my bad. I had no idea the original kubernetes repo was so big.
