### ISSUE TITLE
what's left

### ISSUE THREAD

**Issue by setop** [ibuildthecloud/k3s#3]
A good point is that the readme tells what's been removed. 
For those who do not know k8s features list by heart, it should also tell what's left in k3s.
Nice initiative by the way.

**Comment by ibuildthecloud** [comment]
Good idea, I'll update the docs.

**Comment by ibuildthecloud** [comment]
I really don't want to keep having to update docs to include what is in or out so I'm just going by the rule that what is removed is legacy, alpha, non-default features, and in-tree plugins.  In the end you hopefully shouldn't notice what is missing unless you are an advanced user or you want deep cloud integration (at which point I'd say just buy GKE, AKS, EKS, etc).
