### ISSUE TITLE
Why sqlite3 > etcd?

### ISSUE THREAD

**Issue by jacktuck** [ibuildthecloud/k3s#5]

**Comment by ibuildthecloud** [comment]
It's small.  I've been experimenting with different backends for storage.  To me SQL makes the most sense as I have a lot of flexibility.  So I can do embedded with sqlite, I can get a hosted version of something with RDS, I can run mysql/postgres myself, I can run newsql like CockroachDB or TiDB.

**Comment by jacktuck** [comment]
Thanks for the detailed answer! :)
